### ISSUE TITLE
Error 404 not found (tracker_add_auto.sh)

### ISSUE THREAD

**Issue by AlfonsoReina** [AndrewMarchukov/tracker-add#1]
If you do `wget --no-check-certificate -O /opt/bin/add-trackers-auto.sh https://raw.githubusercontent.com/AndrewMarchukov/tracker-add/master/tracker_add_auto.sh` will get Error 404 not found

Have to change `tracker_add_auto.sh` to `tracker-add-auto.sh`
and `chmod +x /opt/bin/add_trackers_auto.sh` to `add-trackers-auto.sh`

Service didn't run because have to change at file `transmission-tracker-add.service`
line 7, `ExecStart=/opt/bin/add_trackers_auto.sh` to `ExecStart=/opt/bin/add-trackers-auto.sh`

**Comment by AndrewMarchukov** [comment]
Oops, fixed
