### ISSUE TITLE
date errors

### ISSUE THREAD

**Issue by mradzkii** [AndrewMarchukov/tracker-add#14]
used this command
nohup ./tracker-add-auto-router.sh </dev/null >/var/log/tracker-add-auto.log 2>&1 &

/var/log/tracker-add-auto.log 
shows this in the logs

date: invalid option -- 'D'
Try 'date --help' for more information.
date: invalid option -- 'D'
Try 'date --help' for more information.
date: invalid option -- 'D'
Try 'date --help' for more information.
date: invalid option -- 'D'
Try 'date --help' for more information.
date: invalid option -- 'D'
Try 'date --help' for more information.
date: invalid option -- 'D'
Try 'date --help' for more information.

ubuntu 18

**Comment by AndrewMarchukov** [comment]
I recommended use "Systemd way" for ubuntu or take tracker-add-auto.sh and launch as well "nohup ./tracker-add-auto.sh </dev/null >/var/log/tracker-add-auto.log 2>&1 &"
