### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by mradzkii** [AndrewMarchukov/tracker-add#15]
transmission is in docker
transmission-tracker-add is in docker
docker run --net=host -d -e HOSTPORT=localhost:9091 -e TR_AUTH=myuser:mypass --name=transmission-tracker-add andrewmhub/transmission-tracker-add:latest

docker logs --tail 2500 transmission-tracker-add
[2020-05-16 22:38:53.300] transmission-remote:  (http://localhost:9091/transmission/rpc/) Failure when receiving data from the peer

**Comment by mradzkii** [comment]
okay i removed host and added --net=bridge
docker run --net=bridge -d -e HOSTPORT=localhost:9091 -e TR_AUTH=user:pass., --name=transmission-tracker-add andrewmhub/transmission-tracker-add:latest

log shows
 [2020-05-16 23:08:47.191] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-05-16 23:09:12.196] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
[2020-05-16 23:09:37.202] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server

**Comment by AndrewMarchukov** [comment]
show transmission settings.json please

**Comment by ardenyang** [comment]
This is an very cool script, however I also have same issue in recently, I use Docker mode and run very good, however when I upgrate DSM to DSM 6.2.3-25426 at past week, however docker got error: [2020-05-22 04:04:35.218] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server, 

And then I try run ./manual-tracker-add.sh in SSH, I got error: ./manual-tracker-add.sh: line 34: transmission-remote: command not found.

Attached settings.json for your reference. Thanks.

**Comment by AndrewMarchukov** [comment]
1. for the manual-tracker-add.sh you need curl, transmission-remote or\and transmission-cli too
2. in settings.json try set "rpc-url": "/transmission/rpc/"
3. make sure you rpc-password and rpc-username set correctly in both side settings.json and script file

**Comment by ardenyang** [comment]
Thanks for your quickly reply, I try the three steps, but still not work, error message same with before.

 line 36: transmission-remote: command not found
