### ISSUE TITLE
Can I add tracker to a remote server？

### ISSUE THREAD

**Issue by ProteinPig** [AndrewMarchukov/tracker-add#2]
It seems like that the "auth=user:password" option means the scripts ONLY add tracker to the Transmission on localhost.
Can I do that to a remote server such as Transmission deploy in Docker?

**Comment by AndrewMarchukov** [comment]
yes, i added feature "host" and now u can do that

**Comment by ProteinPig** [comment]
Thanks a lot! Should I add the port?

**Comment by AndrewMarchukov** [comment]
set in file: host=myname:4321

**Comment by AndrewMarchukov** [comment]
it is not necessary to add a port, sry i misread question :D

**Comment by AndrewMarchukov** [comment]
everything will be fine
