### ISSUE TITLE
Docker build for linux/arm

### ISSUE THREAD

**Issue by MathyEM** [AndrewMarchukov/tracker-add#21]
I'd love to run this via docker on my Raspberry Pi 4. I'd really appreciate it if you could build the docker image for linux/arm.

For other people coming across this, if you get this error: `standard_init_linux.go:228: exec user process caused: exec format error` the docker image might be the incorrect architecture for your system.

**Comment by liluosheng** [comment]
chmod: cannot access '/opt/bin/add-trackers-auto.sh': No such file or directory

**Comment by AndrewMarchukov** [comment]
done 
https://hub.docker.com/r/andrewmhub/transmission-tracker-add/tags
