### ISSUE TITLE
Please use the -t option first.

### ISSUE THREAD

**Issue by lazychris2000** [AndrewMarchukov/tracker-add#24]
Running on Ubuntu 20.04 with Transmission 3.00.
Running script as-is will result in nothing but 'No torrent specified' errors:

```
 * udp://tracker.opentrackr.org:1337/announce...No torrent specified!  Please use the -t option first.
 done.
* http://tracker.opentrackr.org:1337/announce...No torrent specified!  Please use the -t option first.
 done.
* udp://open.tracker.cl:1337/announce...No torrent specified!  Please use the -t option first.
 done.
* udp://9.rarbg.com:2810/announce...No torrent specified!  Please use the -t option first.
 done.
* udp://opentracker.i2p.rocks:6969/announce...No torrent specified!  Please use the -t option first.
 done.
* https://opentracker.i2p.rocks:443/announce...No torrent specified!  Please use the -t option first.
 done.
* udp://tracker.torrent.eu.org:451/announce...No torrent specified!  Please use the -t option first.
 done.
[...]
```

Doing a little poking around the script and some trial and error, I had to change
`ids=${1:-"$(transmission-remote "$host" ${auth:+--auth="$auth"} --list | grep -vE 'Seeding|Stopped|Finished' | grep '^ ' | awk '{ print $1 }')"}`
to 
`ids=${1:-"$(transmission-remote "$host" ${auth:+--auth="$auth"} --list | grep -vE 'ID|Seeding|Stopped|Finished' | grep '^ ' | awk '{ print $1 }')"}`

It seems that before making that change, the first thing listed in $ids would be "ID" instead of an ID number and transmission threw a fit.

Thanks for all your work making this script! I hope this will help if anyone else is having this problem.

**Comment by AndrewMarchukov** [comment]
this is not a error, this grep take only "Running" torrents

**Comment by lazychris2000** [comment]
I didn't realize that. My mistake. Thank you for the explanation
