### ISSUE TITLE
Debug docker

### ISSUE THREAD

**Issue by vincentcox** [AndrewMarchukov/tracker-add#6]
Hi there,

Running it manually it works perfectly. I use the docker command, but it doesn't seem to add the trackers. I haven't found a way to debug it. Via command line, it gives no output. Where can i see what is going wrong? Thanks.

**Comment by AndrewMarchukov** [comment]
http://www.littlebigextra.com/view-docker-container-logs/

**Comment by vincentcox** [comment]
Thanks but I was aware of that.
That command doesn't return any output, however on other docker containers it does. Therefore I was wondering where it keeps his logs so I can shell into it.

**Comment by AndrewMarchukov** [comment]
Logs should be there
Make sure you have the right environment variables

**Comment by vincentcox** [comment]
still no idea where to look for logs. 

```Status: Downloaded newer image for andrewmhub/transmission-tracker-add:latest
8a67f5c3c90407366215a1610ad450ec37ab3f0b4f2ca148594457fbdbe5966a
[~] # docker logs --tail 2500 8a67f5c3c90407366215a1610ad450ec37ab3f0b4f2ca148594457fbdbe5966a
error from daemon in stream: Error grabbing logs: EOF
