### ISSUE TITLE
What to do for help?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [AndrewMarchukov/tracker-add#9]
........../announce...No torrent specified!  Please use the -t option first.

**Comment by AndrewMarchukov** [comment]
maybe you need edit settings.json for transmission set rpc-enabled, rpc-username and rpc-password and then set user and password in add-trackers-auto.sh
or what you truing to do?

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> maybe you need edit settings.json for transmission set rpc-enabled, rpc-username and rpc-password and then set user and password in add-trackers-auto.sh
> or what you truing to do?

Thanks i solved it myself
Need to modify the following
Line 7: torrent_hash = all
Successfully done, haha, happy ~~~

**Comment by AndrewMarchukov** [comment]
torrent hash is calculate value:
hash="$(transmission-remote "$host" --auth="$auth"  --torrent "$id" --info | grep '^  Hash: ' | awk '{ print $2 }')"
